AAP-13348 Fix UnknownUUID ID is not a valid uuid
redhat-cop/infra.osbuild pull request #217
Opened 2023-06-19 15:03 UTC by de1987

# Description
Fix UnknownUUID ID is not a valid uuid

FIXES: [AAP-13348](https://issues.redhat.com/browse/AAP-13348)

## Type of change

What is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Tests update
- [ ] Refactor

2023-06-20 19:12 UTC, resoluteCoder approved these changes

2023-06-21 09:32 UTC, thom-at-redhat requested changes
Missing Changelog fragment file, please provide

2023-06-22 20:01 UTC, de1987 commented
> Missing Changelog fragment file, please provide

Done

2023-06-22 20:46 UTC, thom-at-redhat approved these changes

2023-06-22 20:49 UTC, thom-at-redhat approved these changes

2023-06-23 14:43 UTC, de1987 commented
@mergify rebase

2023-06-23 17:32 UTC, merged